name: lints

on: pull_request

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install gnome-keyring
        # https://github.com/python-poetry/poetry/issues/2692
        run: sudo apt-get install gnome-keyring

      - name: Install poetry
        run: pip install --user poetry

      - name: Run poetry check
        run: poetry check

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run flake8
        run: poetry run flake8

      - name: Run pyanalyze
        # `poetry run pyanalyze .` doesn't work in CI for some reason.
        run: poetry run python -m pyanalyze .
